export const CERTIFICATES = [
  { value: "ACSM", label: "American College of Sports Medicine (ACSM) Certified" },
  { value: "ACE", label: "American Council On Exercise (ACE) Certified " },
  {
    value: "NSCA",
    label: "National Strength and Conditioning Association (NSCA) Certified",
  },
  { value: "NASM", label: "National Academy of Sports Medicine (NASM) Certified" },
  {
    value: "ISSM",
    label: "International Sports Sciences Association (ISSM) Certified",
  },
]

export const TRAININGS = [
  { value: "Indoor Bike", label: "Indoor Bike" },
  { value: "Elliptical", label: "Elliptical" },
  { value: "Indoor Run", label: "Indoor Run" },
  { value: "Indoor Walk", label: "Indoor Walk" },
  { value: "Jump Rope", label: "Jump Rope" },
  { value: "Dance", label: "Dance" },
  { value: "HIIT Workout", label: "HIIT Workout" },
  { value: "Boxing", label: "Boxing" },
  { value: "Weight Training", label: "Weight Training" },
  { value: "Core Training", label: "Core Training" },
  { value: "Cross Training", label: "Cross Training" },
  { value: "Yoga", label: "Yoga" },
  { value: "Pilates", label: "Pilates" },
]

export const TIMEZONES = [
  { label: "Central Daylight Time Chicago (GMT-5)", value: "CDT" },
  { label: "Mountain Daylight Time Denver(GMT-6)", value: "MDT" },
  { label: "Mountain Standard Time Phoenix (GMT-7)", value: "MST" },
  { label: "Pacific Daylight Time Los Angeles (GMT-7)", value: "PDT" },
  { label: "Alaska Daylight Time Anchorage (GMT-8)", value: "ADT" },
  { label: "Hawaii-Aleutian Standard Time Honolulu(GMT-10)", value: "HAST" },
]

export const STATES = [
  { label: 'Alabama', value: 'AL'},
  { label: 'Alaska', value: 'AK'},
  { label: 'Arizona', value: 'AZ'},
  { label: 'Arkansas', value: 'AR'},
  { label: 'California', value: 'CA'},
  { label: 'Colorado', value: 'CO'},
  { label: 'Connecticut', value: 'CT'},
  { label: 'Delaware', value: 'DE'},
  { label: 'Florida', value: 'FL'},
  { label: 'Georgia', value: 'GA'},
  { label: 'Hawaii', value: 'HI'},
  { label: 'Idaho', value: 'ID'},
  { label: 'Illinois', value: 'IL'},
  { label: 'Indiana', value: 'IN'},
  { label: 'Iowa', value: 'IA'},
  { label: 'Kansas', value: 'KS'},
  { label: 'Kentucky[E]', value: 'KY'},
  { label: 'Louisiana', value: 'LA'},
  { label: 'Maine', value: 'ME'},
  { label: 'Maryland', value: 'MD'},
  { label: 'Massachusetts[E]', value: 'MA'},
  { label: 'Michigan', value: 'MI'},
  { label: 'Minnesota', value: 'MN'},
  { label: 'Mississippi', value: 'MS'},
  { label: 'Missouri', value: 'MO'},
  { label: 'Montana', value: 'MT'},
  { label: 'Nebraska', value: 'NE'},
  { label: 'Nevada', value: 'NV'},
  { label: 'New Hampshire', value: 'NH'},
  { label: 'New Jersey', value: 'NJ'},
  { label: 'New Mexico', value: 'NM'},
  { label: 'New York', value: 'NY'},
  { label: 'North Carolina', value: 'NC'},
  { label: 'North Dakota', value: 'ND'},
  { label: 'Ohio', value: 'OH'},
  { label: 'Oklahoma', value: 'OK'},
  { label: 'Oregon', value: 'OR'},
  { label: 'Pennsylvania[E]', value: 'PA'},
  { label: 'Rhode Island[F]', value: 'RI'},
  { label: 'South Carolina', value: 'SC'},
  { label: 'South Dakota', value: 'SD'},
  { label: 'Tennessee', value: 'TN'},
  { label: 'Texas', value: 'TX'},
  { label: 'Utah', value: 'UT'},
  { label: 'Vermont', value: 'VT'},
  { label: 'Virginia[E]', value: 'VA'},
  { label: 'Washington', value: 'WA'},
  { label: 'West Virginia', value: 'WV'},
  { label: 'Wisconsin', value: 'WI'},
  { label: 'Wyoming', value: 'WY'},
]