export const AUTH = {
  SIGNED_IN: "SIGNED_IN",
  SIGNED_OUT: "SIGNED_OUT",
  USER_PROFILE: "USER_PROFILE",
  USER_INFO: "USER_INFO",
  OPEN_LOGIN_MODAL: "OPEN_LOGIN_MODAL",
  CLOSE_LOGIN_MODAL: "CLOSE_LOGIN_MODAL",
  REMOVE_GALLERY: "REMOVE_GALLERY",
}

export const STRIPE = {
  OPEN_STRIPE_MODAL: "OPEN_STRIPE_MODAL",
  CLOSE_STRIPE_MODAL: "CLOSE_STRIPE_MODAL",
}

export const COMMON = {
  TOSTIFY_ALERT_FUNC: "TOSTIFY_ALERT_FUNC",
  TOSTIFY_ALERT: "TOSTIFY_ALERT",
  SET_PERMISSION: "SET_PERMISSION",
}

export const WORKOUT = {
  WORKOUT_SESSIONS: "WORKOUT_SESSIONS",
}
