export const AUTH = {
  SIGNED_IN: "SIGNED_IN",
  SIGNED_OUT: "SIGNED_OUT",
  USER_PROFILE: "USER_PROFILE",
}

export const COMMON = {
  TOSTIFY_ALERT_FUNC: "TOSTIFY_ALERT_FUNC",
  TOSTIFY_ALERT: "TOSTIFY_ALERT",
  SET_PERMISSION: "SET_PERMISSION",
}
